"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ltimujpov(p(6xly%ffk50hi#d_%b1zkn!l_bqrput5#ps__5g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp.apps.MyappConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'
import os

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

import os

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_URL = '/static/'
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
JAZZMIN_SETTINGS = {

    "site_icon" : "AdminLTELogo.png",
    "site_logo_classes": "img-circle",
    "welcome_sign": "Welcome To Revolutionizing Agriculture",
    "copyright": "Revolutionizing Agriculture",
    "search_model": ["myapp.customer", "myapp.productcategory", "myapp.product"],
    "topmenu_links": [
        {"name": "home", "url": "admin:index", "icons": "fas fa-house-user"},
        # external url that opens in a new window (Permissions can be added)
        # model admin to link to (Permissions checked against model)
        {"model": "myapp.customer"},
        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "myapp"}
    ],
    "hide_models": "",
    "custom_links": {
        "myapp": [{
            "name": "Visit the website",
            "url": 'index',
            "icon": "fas fa-bell",

        }]
    },
    "icons": {
        "auth.User": "far fa-user-circle",
        "auth.Group": "fas fa-layer-group",
        "myapp.city": "fas fa-city",
        "myapp.area": "fas fa-warehouse",
        "myapp.cart": "fa fa-cart-plus",
        "myapp.company": "	fas fa-building",
        "myapp.customer": "far fa-user",
        "myapp.productcategory": "fas fa-seedling",
        "myapp.product": "fas fa-seedling",
        "myapp.salesorder": "fas fa-weight-hanging",
        "myapp.salesorder_detail": "fas fa-shopping-cart",
        "myapp.supplier": "fas fa-shipping-fast",
        "myapp.payment": "fas fa-credit-card",
        "myapp.rentmachinery": "fas fa-cogs",
        "myapp.feedback1": "fas fa-comments",
        "myapp.report1": "fas fa-chart-bar",
        "myapp.filter" : "fas fa-dollar-sign",

    },
"changeform_format": "carousel",
    "show_ui_builder": False

}

if DEBUG:

    STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

else:

    STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_USE_SSL = True
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'karinapatel615@gmail.com'
EMAIL_HOST_PASSWORD = 'hrlv cztk tbgd herd'
EMAIL_PORT = 587


