# Generated by Django 5.0.1 on 2024-01-23 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='prodsubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='productcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.DecimalField(decimal_places=0, max_digits=6)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('city_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('contact', models.DecimalField(decimal_places=0, max_digits=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('area_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.area')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.DecimalField(decimal_places=0, max_digits=10, unique=True)),
                ('address', models.TextField()),
                ('area_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.area')),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='photos')),
                ('price', models.IntegerField()),
                ('manufacturedate', models.DateField(blank=True)),
                ('expirydate', models.DateField(blank=True, null=True)),
                ('filter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.filter')),
                ('prodsubcategory_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.prodsubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='feedback1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('customer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.customer')),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('totalprice', models.IntegerField(null=True)),
                ('product_status', models.IntegerField(null=True)),
                ('orderid', models.IntegerField(null=True)),
                ('customer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.customer')),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='prodsubcategory',
            name='productcategory_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.productcategory'),
        ),
        migrations.CreateModel(
            name='report1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='salesorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('delivery_address', models.TextField(null=True)),
                ('iscancel', models.BooleanField()),
                ('totalamount', models.IntegerField()),
                ('order_status', models.CharField(choices=[('1', 'Confirm'), ('2', 'Pending'), ('3', 'Out of delivery'), ('4', 'Delivered'), ('5', 'Canceled'), ('6', 'Returned')], default='Confirm', max_length=40)),
                ('payment_status', models.BooleanField()),
                ('paymentmode', models.CharField(default='Cash On Delivery', max_length=40)),
                ('customer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('payment_type', models.BooleanField()),
                ('total_amount', models.IntegerField()),
                ('customer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.customer')),
                ('saleorder_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='salesorder_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.product')),
                ('salesorder_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('contact', models.DecimalField(decimal_places=0, max_digits=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('area_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.area')),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.company')),
                ('prodct_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='rentMachinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeDuration', models.DateTimeField()),
                ('rentAmount', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.customer')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.product')),
                ('supplier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.supplier')),
            ],
        ),
    ]
