# Generated by Django 5.0.1 on 2024-01-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentmachinery',
            old_name='rentAmount',
            new_name='rent_amount',
        ),
        migrations.RenameField(
            model_name='rentmachinery',
            old_name='timeDuration',
            new_name='time_duration',
        ),
    ]
