# Generated by Django 5.0.1 on 2024-01-24 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_rentamount_rentmachinery_rent_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company_name',
        ),
    ]
