# Generated by Django 5.0.1 on 2024-01-28 07:20

import django.core.validators
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_customer_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='prodsubcategory',
            name='image',
            field=models.ImageField(upload_to='photos', validators=[myapp.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='photos', validators=[myapp.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(upload_to='photos', validators=[myapp.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='paymentmode',
            field=models.CharField(choices=[('1', 'Cash On Delivery'), ('2', 'UPI'), ('3', 'Card')], max_length=40),
        ),
        migrations.AlterField(
            model_name='salesorder_detail',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
