# Generated by Django 4.1.5 on 2024-02-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentmachinery',
            name='rent_amount',
            field=models.IntegerField(default=500),
        ),
    ]
