# Generated by Django 4.1.5 on 2024-02-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_rentmachinery_rent_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentmachinery',
            name='deposit',
            field=models.IntegerField(null=True),
        ),
    ]
