# Generated by Django 4.1.5 on 2024-02-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_rentmachinery_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentmachinery',
            name='deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
