# Generated by Django 4.1.5 on 2024-02-01 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_rentmachinery_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentmachinery',
            name='rent_amount',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=10000)]),
        ),
    ]
