# Generated by Django 4.1.5 on 2024-02-04 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_rentmachinery_time_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='Subcatgeory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodsubcategory_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.productcategory'),
        ),
        migrations.DeleteModel(
            name='prodsubcategory',
        ),
    ]
