# Generated by Django 4.1.5 on 2024-02-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_productcategory_subcatgeory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodsubcategory_name',
            new_name='prodcategory_name',
        ),
    ]
