# Generated by Django 4.1.5 on 2024-02-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_prodsubcategory_name_product_prodcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
