# Generated by Django 4.1.5 on 2024-02-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_product_manufacturedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodcategory_name',
            new_name='Category',
        ),
    ]
