# Generated by Django 4.1.5 on 2024-02-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_prodcategory_name_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='Subcatgeory',
            new_name='Subcategory',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
