# Generated by Django 4.1.5 on 2024-03-04 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_subcatgeory_productcategory_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='area_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
