# Generated by Django 4.1.5 on 2024-03-04 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_payment_saleorder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback1',
            name='saleorder_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.salesorder_detail'),
        ),
    ]
