# Generated by Django 4.1.5 on 2024-03-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_feedback1_saleorder_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorder_detail',
            old_name='salesorder_id',
            new_name='salesorder_name',
        ),
    ]
