# Generated by Django 4.1.5 on 2024-03-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rename_salesorder_id_salesorder_detail_salesorder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ava_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
