# Generated by Django 4.1.5 on 2024-03-16 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_product_ava_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='order_status',
        ),
        migrations.CreateModel(
            name='Order_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('1', 'Waiting for Accept'), ('2', 'Accepted'), ('3', 'Start Cooking'), ('4', 'Packaged'), ('5', 'Ready for Delivery'), ('6', 'Out for delivery'), ('7', 'Delivered'), ('8', 'Canceled')], max_length=30)),
                ('salesorder_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.salesorder')),
            ],
        ),
    ]
