# Generated by Django 4.2.4 on 2024-03-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0021_remove_salesorder_order_status_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentmachinery",
            name="booked_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="order_status",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "Waiting for Accept"),
                    ("2", "Accepted"),
                    ("3", "Delivered"),
                    ("4", "Canceled"),
                ],
                max_length=30,
            ),
        ),
    ]
