# Generated by Django 4.2.4 on 2024-03-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0022_rentmachinery_booked_date_alter_order_status_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentmachinery",
            name="time_duration",
            field=models.CharField(max_length=30),
        ),
    ]
