# Generated by Django 4.2.4 on 2024-03-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0023_alter_rentmachinery_time_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentmachinery",
            name="payment_type",
            field=models.CharField(default="Cash On Delivery", max_length=20),
        ),
    ]
